name: Build Chatsentinel
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 11, 8]
      fail-fast: true
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: CHMOD
        run: chmod 777 pom.xml
      - name: build
        run: mvn clean install
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ChatSentinel${{ matrix.java }}
          path: target/ChatSentinel.jar
